name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Check commit message for 'production'
      id: check_production
      run: echo "::set-output name=deploy_flag::$(if git log --format=%B -n 1 $GITHUB_SHA | grep -qi 'production'; then echo true; else echo false; fi)"
    - name: Deploy
      if: steps.check_production.outputs.deploy_flag == 'true'
      run: pm2 restart index.js
